version: '3.8'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./cert/:/etc/nginx/ssl/:ro
    # network_mode: "host"
    extra_hosts:
     - "host.docker.internal:localhost"
