version: '3.1'
services:
  webserver:
    image: nginx:latest  	
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./cert/:/etc/nginx/ssl/:ro


