version: '3.8'
services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis/cache/:/data/
    network_mode: "host"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    network_mode: "host"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@sql.net
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "3657:80"
  
  auth:
    image: auth-server
    restart: always
    ports:
      - "5052:5052"
    depends_on:
      - cache
    network_mode: "host"

  biz:
    image: biz-server
    restart: always
    ports:
      - "5062:5062"
    depends_on:
      - postgres
    network_mode: "host"

  gateway:
    image: gateway-server
    restart: always
    ports:
      - "6443:6443"
    network_mode: "host"