// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: auth/auth.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthenticatorClient is the client API for Authenticator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenticatorClient interface {
	RequestPQ(ctx context.Context, in *PQRequest, opts ...grpc.CallOption) (*PQResponse, error)
	RequestDHParams(ctx context.Context, in *DHRequest, opts ...grpc.CallOption) (*DHResponse, error)
	AuthCheck(ctx context.Context, in *ACRequest, opts ...grpc.CallOption) (*ACResponce, error)
}

type authenticatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticatorClient(cc grpc.ClientConnInterface) AuthenticatorClient {
	return &authenticatorClient{cc}
}

func (c *authenticatorClient) RequestPQ(ctx context.Context, in *PQRequest, opts ...grpc.CallOption) (*PQResponse, error) {
	out := new(PQResponse)
	err := c.cc.Invoke(ctx, "/Authenticator/RequestPQ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticatorClient) RequestDHParams(ctx context.Context, in *DHRequest, opts ...grpc.CallOption) (*DHResponse, error) {
	out := new(DHResponse)
	err := c.cc.Invoke(ctx, "/Authenticator/RequestDHParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticatorClient) AuthCheck(ctx context.Context, in *ACRequest, opts ...grpc.CallOption) (*ACResponce, error) {
	out := new(ACResponce)
	err := c.cc.Invoke(ctx, "/Authenticator/authCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticatorServer is the server API for Authenticator service.
// All implementations must embed UnimplementedAuthenticatorServer
// for forward compatibility
type AuthenticatorServer interface {
	RequestPQ(context.Context, *PQRequest) (*PQResponse, error)
	RequestDHParams(context.Context, *DHRequest) (*DHResponse, error)
	AuthCheck(context.Context, *ACRequest) (*ACResponce, error)
	mustEmbedUnimplementedAuthenticatorServer()
}

// UnimplementedAuthenticatorServer must be embedded to have forward compatible implementations.
type UnimplementedAuthenticatorServer struct {
}

func (UnimplementedAuthenticatorServer) RequestPQ(context.Context, *PQRequest) (*PQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPQ not implemented")
}
func (UnimplementedAuthenticatorServer) RequestDHParams(context.Context, *DHRequest) (*DHResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDHParams not implemented")
}
func (UnimplementedAuthenticatorServer) AuthCheck(context.Context, *ACRequest) (*ACResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthCheck not implemented")
}
func (UnimplementedAuthenticatorServer) mustEmbedUnimplementedAuthenticatorServer() {}

// UnsafeAuthenticatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenticatorServer will
// result in compilation errors.
type UnsafeAuthenticatorServer interface {
	mustEmbedUnimplementedAuthenticatorServer()
}

func RegisterAuthenticatorServer(s grpc.ServiceRegistrar, srv AuthenticatorServer) {
	s.RegisterService(&Authenticator_ServiceDesc, srv)
}

func _Authenticator_RequestPQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).RequestPQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authenticator/RequestPQ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).RequestPQ(ctx, req.(*PQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticator_RequestDHParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).RequestDHParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authenticator/RequestDHParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).RequestDHParams(ctx, req.(*DHRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticator_AuthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).AuthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authenticator/authCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).AuthCheck(ctx, req.(*ACRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authenticator_ServiceDesc is the grpc.ServiceDesc for Authenticator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authenticator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Authenticator",
	HandlerType: (*AuthenticatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPQ",
			Handler:    _Authenticator_RequestPQ_Handler,
		},
		{
			MethodName: "RequestDHParams",
			Handler:    _Authenticator_RequestDHParams_Handler,
		},
		{
			MethodName: "authCheck",
			Handler:    _Authenticator_AuthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
