// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: auth/auth.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ReqPq_RequestPQ_FullMethodName = "/req_pq/RequestPQ"
)

// ReqPqClient is the client API for ReqPq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReqPqClient interface {
	RequestPQ(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type reqPqClient struct {
	cc grpc.ClientConnInterface
}

func NewReqPqClient(cc grpc.ClientConnInterface) ReqPqClient {
	return &reqPqClient{cc}
}

func (c *reqPqClient) RequestPQ(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, ReqPq_RequestPQ_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReqPqServer is the server API for ReqPq service.
// All implementations must embed UnimplementedReqPqServer
// for forward compatibility
type ReqPqServer interface {
	RequestPQ(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedReqPqServer()
}

// UnimplementedReqPqServer must be embedded to have forward compatible implementations.
type UnimplementedReqPqServer struct {
}

func (UnimplementedReqPqServer) RequestPQ(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPQ not implemented")
}
func (UnimplementedReqPqServer) mustEmbedUnimplementedReqPqServer() {}

// UnsafeReqPqServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReqPqServer will
// result in compilation errors.
type UnsafeReqPqServer interface {
	mustEmbedUnimplementedReqPqServer()
}

func RegisterReqPqServer(s grpc.ServiceRegistrar, srv ReqPqServer) {
	s.RegisterService(&ReqPq_ServiceDesc, srv)
}

func _ReqPq_RequestPQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReqPqServer).RequestPQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReqPq_RequestPQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReqPqServer).RequestPQ(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ReqPq_ServiceDesc is the grpc.ServiceDesc for ReqPq service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReqPq_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "req_pq",
	HandlerType: (*ReqPqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPQ",
			Handler:    _ReqPq_RequestPQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
