// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: biz.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Get_Users_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    *int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`    // user's id
	AuthKey   string `protobuf:"bytes,3,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`        // user's authentication key
	MessageId int64  `protobuf:"varint,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // even and greater than zero
}

func (x *Get_Users_Req) Reset() {
	*x = Get_Users_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Users_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Users_Req) ProtoMessage() {}

func (x *Get_Users_Req) ProtoReflect() protoreflect.Message {
	mi := &file_biz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Users_Req.ProtoReflect.Descriptor instead.
func (*Get_Users_Req) Descriptor() ([]byte, []int) {
	return file_biz_proto_rawDescGZIP(), []int{0}
}

func (x *Get_Users_Req) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *Get_Users_Req) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *Get_Users_Req) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type Get_User_Sql_Inj_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    *string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`     // user's id
	AuthKey   string  `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`        // user's authentication key
	MessageId int64   `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // even and greater than zero
}

func (x *Get_User_Sql_Inj_Req) Reset() {
	*x = Get_User_Sql_Inj_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_User_Sql_Inj_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_User_Sql_Inj_Req) ProtoMessage() {}

func (x *Get_User_Sql_Inj_Req) ProtoReflect() protoreflect.Message {
	mi := &file_biz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_User_Sql_Inj_Req.ProtoReflect.Descriptor instead.
func (*Get_User_Sql_Inj_Req) Descriptor() ([]byte, []int) {
	return file_biz_proto_rawDescGZIP(), []int{1}
}

func (x *Get_User_Sql_Inj_Req) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Get_User_Sql_Inj_Req) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *Get_User_Sql_Inj_Req) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type Get_Users_Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users     []string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`                           // array of users
	MessageId int64    `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // odd and greater than zero
}

func (x *Get_Users_Resp) Reset() {
	*x = Get_Users_Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Users_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Users_Resp) ProtoMessage() {}

func (x *Get_Users_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_biz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Users_Resp.ProtoReflect.Descriptor instead.
func (*Get_Users_Resp) Descriptor() ([]byte, []int) {
	return file_biz_proto_rawDescGZIP(), []int{2}
}

func (x *Get_Users_Resp) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Get_Users_Resp) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

var File_biz_proto protoreflect.FileDescriptor

var file_biz_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x69, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75,
	0x74, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x22, 0x7a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x53, 0x71, 0x6c,
	0x5f, 0x49, 0x6e, 0x6a, 0x5f, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x4b, 0x65,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x32, 0x78, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x2d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x2e, 0x47,
	0x65, 0x74, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x47,
	0x65, 0x74, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x3c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x53, 0x71, 0x6c, 0x5f,
	0x49, 0x6e, 0x6a, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x53,
	0x71, 0x6c, 0x5f, 0x49, 0x6e, 0x6a, 0x5f, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x47, 0x65, 0x74,
	0x5f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x04, 0x5a,
	0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_biz_proto_rawDescOnce sync.Once
	file_biz_proto_rawDescData = file_biz_proto_rawDesc
)

func file_biz_proto_rawDescGZIP() []byte {
	file_biz_proto_rawDescOnce.Do(func() {
		file_biz_proto_rawDescData = protoimpl.X.CompressGZIP(file_biz_proto_rawDescData)
	})
	return file_biz_proto_rawDescData
}

var file_biz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_biz_proto_goTypes = []interface{}{
	(*Get_Users_Req)(nil),        // 0: Get_Users_Req
	(*Get_User_Sql_Inj_Req)(nil), // 1: Get_User_Sql_Inj_Req
	(*Get_Users_Resp)(nil),       // 2: Get_Users_Resp
}
var file_biz_proto_depIdxs = []int32{
	0, // 0: Get_Users.GetUsers:input_type -> Get_Users_Req
	1, // 1: Get_Users.Get_User_Sql_Inj:input_type -> Get_User_Sql_Inj_Req
	2, // 2: Get_Users.GetUsers:output_type -> Get_Users_Resp
	2, // 3: Get_Users.Get_User_Sql_Inj:output_type -> Get_Users_Resp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_biz_proto_init() }
func file_biz_proto_init() {
	if File_biz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Users_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_User_Sql_Inj_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Users_Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_biz_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_biz_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_biz_proto_goTypes,
		DependencyIndexes: file_biz_proto_depIdxs,
		MessageInfos:      file_biz_proto_msgTypes,
	}.Build()
	File_biz_proto = out.File
	file_biz_proto_rawDesc = nil
	file_biz_proto_goTypes = nil
	file_biz_proto_depIdxs = nil
}
