# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\".\n\tPQRequest\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\x03\"[\n\nPQResponse\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x03\x12\t\n\x01p\x18\x04 \x01(\x03\x12\t\n\x01g\x18\x05 \x01(\x03\"O\n\tDHRequest\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x03\x12\t\n\x01\x61\x18\x04 \x01(\x03\"P\n\nDHResponse\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x03\x12\t\n\x01\x62\x18\x04 \x01(\x03\"V\n\tACRequest\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x03\x12\x10\n\x08\x61uth_key\x18\x04 \x01(\x03\"4\n\nACResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\x03\x12\x12\n\nauth_check\x18\x02 \x01(\x08\x32\x8d\x01\n\rAuthenticator\x12&\n\tRequestPQ\x12\n.PQRequest\x1a\x0b.PQResponse\"\x00\x12,\n\x0fRequestDHParams\x12\n.DHRequest\x1a\x0b.DHResponse\"\x00\x12&\n\tAuthCheck\x12\n.ACRequest\x1a\x0b.ACResponse\"\x00\x42\x04Z\x02./b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _PQREQUEST._serialized_start=14
  _PQREQUEST._serialized_end=60
  _PQRESPONSE._serialized_start=62
  _PQRESPONSE._serialized_end=153
  _DHREQUEST._serialized_start=155
  _DHREQUEST._serialized_end=234
  _DHRESPONSE._serialized_start=236
  _DHRESPONSE._serialized_end=316
  _ACREQUEST._serialized_start=318
  _ACREQUEST._serialized_end=404
  _ACRESPONSE._serialized_start=406
  _ACRESPONSE._serialized_end=458
  _AUTHENTICATOR._serialized_start=461
  _AUTHENTICATOR._serialized_end=602
# @@protoc_insertion_point(module_scope)
