# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import biz_pb2 as biz__pb2


class BizServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsers = channel.unary_unary(
                '/BizService/GetUsers',
                request_serializer=biz__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=biz__pb2.GetUsersResponse.FromString,
                )
        self.GetUsersWithSQL = channel.unary_unary(
                '/BizService/GetUsersWithSQL',
                request_serializer=biz__pb2.GetUsersWithSQLRequest.SerializeToString,
                response_deserializer=biz__pb2.GetUsersResponse.FromString,
                )


class BizServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersWithSQL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BizServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=biz__pb2.GetUsersRequest.FromString,
                    response_serializer=biz__pb2.GetUsersResponse.SerializeToString,
            ),
            'GetUsersWithSQL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersWithSQL,
                    request_deserializer=biz__pb2.GetUsersWithSQLRequest.FromString,
                    response_serializer=biz__pb2.GetUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BizService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BizService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BizService/GetUsers',
            biz__pb2.GetUsersRequest.SerializeToString,
            biz__pb2.GetUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsersWithSQL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BizService/GetUsersWithSQL',
            biz__pb2.GetUsersWithSQLRequest.SerializeToString,
            biz__pb2.GetUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
